<?php
if ( ! defined( 'ABSPATH' ) ) { exit; }
class VH360_Studio_Bible_Admin {
    public function __construct() { add_action( 'admin_menu', array( $this, 'menu' ), 30 ); add_action( 'admin_enqueue_scripts', array( $this, 'assets' ) ); }
    public function menu() { $parent = menu_page_url( 'vh360-studio-settings', false ) ? 'vh360-studio-settings' : 'options-general.php'; add_submenu_page( $parent, __( 'Bible Library', 'videohub360-studio' ), __( 'Bible Library', 'videohub360-studio' ), 'manage_options', 'vh360-studio-bible', array( $this, 'render' ) ); }
    public function assets( $hook ) { if ( false === strpos( $hook, 'vh360-studio-bible' ) ) { return; } $p = 'assets/admin/studio-bible-admin.js'; wp_enqueue_script( 'vh360-studio-bible-admin', VH360_STUDIO_PLUGIN_URL . $p, array(), VH360_STUDIO_VERSION . '-' . filemtime( VH360_STUDIO_PLUGIN_DIR . $p ), true ); wp_localize_script( 'vh360-studio-bible-admin', 'vh360StudioBibleAdmin', array( 'restRoot' => esc_url_raw( rest_url( 'vh360-studio/v1' ) ), 'nonce' => wp_create_nonce( 'wp_rest' ), 'strings' => array( 'uploading' => __( 'Uploading…', 'videohub360-studio' ), 'requestFailed' => __( 'Request failed.', 'videohub360-studio' ), 'confirmDelete' => __( 'Delete this translation and all of its verses?', 'videohub360-studio' ), 'status' => __( 'Status', 'videohub360-studio' ), 'processed' => __( 'Processed', 'videohub360-studio' ), 'imported' => __( 'Imported', 'videohub360-studio' ), 'omitted' => __( 'Omitted', 'videohub360-studio' ), 'failed' => __( 'Failed', 'videohub360-studio' ), 'books' => __( 'Books', 'videohub360-studio' ) ) ) ); }
    public function render() {
        $repo = new VH360_Studio_Bible_Repository();
        echo '<div class="wrap"><h1>' . esc_html__( 'Bible Library', 'videohub360-studio' ) . '</h1><table class="widefat"><thead><tr><th>' . esc_html__( 'Translation', 'videohub360-studio' ) . '</th><th>' . esc_html__( 'Abbreviation', 'videohub360-studio' ) . '</th><th>' . esc_html__( 'Language', 'videohub360-studio' ) . '</th><th>' . esc_html__( 'Status', 'videohub360-studio' ) . '</th><th>' . esc_html__( 'Books', 'videohub360-studio' ) . '</th><th>' . esc_html__( 'Verses', 'videohub360-studio' ) . '</th><th>' . esc_html__( 'Actions', 'videohub360-studio' ) . '</th></tr></thead><tbody>';
        foreach ( $repo->list_all_translations() as $tr ) {
            echo '<tr><td>' . esc_html( $tr['name'] ) . '</td><td>' . esc_html( $tr['abbreviation'] ) . '</td><td>' . esc_html( $tr['language'] ) . '</td><td>' . esc_html( $tr['status'] ) . '</td><td>' . esc_html( $tr['bookCount'] ) . '</td><td>' . esc_html( $tr['verseCount'] ) . '</td><td>';
            if ( 'disabled' === $tr['status'] ) { echo '<button type="button" class="button" data-bible-admin-action="enable" data-key="' . esc_attr( $tr['translationKey'] ) . '">' . esc_html__( 'Enable', 'videohub360-studio' ) . '</button> '; }
            if ( 'installed' === $tr['status'] ) { echo '<button type="button" class="button" data-bible-admin-action="disable" data-key="' . esc_attr( $tr['translationKey'] ) . '">' . esc_html__( 'Disable', 'videohub360-studio' ) . '</button> '; }
            echo '<button type="button" class="button button-link-delete" data-bible-admin-action="delete" data-key="' . esc_attr( $tr['translationKey'] ) . '">' . esc_html__( 'Delete', 'videohub360-studio' ) . '</button></td></tr>';
        }
        echo '</tbody></table>';
        $importer = new VH360_Studio_Bible_Importer();
        echo '<h2>' . esc_html__( 'Import jobs', 'videohub360-studio' ) . '</h2><table class="widefat"><thead><tr><th>' . esc_html__( 'ID', 'videohub360-studio' ) . '</th><th>' . esc_html__( 'Translation', 'videohub360-studio' ) . '</th><th>' . esc_html__( 'Status', 'videohub360-studio' ) . '</th><th>' . esc_html__( 'Processed', 'videohub360-studio' ) . '</th><th>' . esc_html__( 'Imported', 'videohub360-studio' ) . '</th><th>' . esc_html__( 'Omitted', 'videohub360-studio' ) . '</th><th>' . esc_html__( 'Failed', 'videohub360-studio' ) . '</th><th>' . esc_html__( 'Errors', 'videohub360-studio' ) . '</th><th>' . esc_html__( 'Actions', 'videohub360-studio' ) . '</th></tr></thead><tbody>';
        foreach ( $importer->list_jobs() as $job ) { $payload = json_decode( $job['error_message'], true ); $errors = isset( $payload['errors'] ) ? (array) $payload['errors'] : array(); echo '<tr><td>' . esc_html( $job['id'] ) . '</td><td>' . esc_html( $job['translation_key'] ) . '</td><td>' . esc_html( $job['status'] ) . '</td><td>' . esc_html( $job['rows_processed'] ) . '</td><td>' . esc_html( $job['rows_imported'] ) . '</td><td>' . esc_html( $job['rows_omitted'] ) . '</td><td>' . esc_html( $job['rows_failed'] ) . '</td><td><details><summary>' . esc_html__( 'View errors', 'videohub360-studio' ) . '</summary><pre>' . esc_html( implode( "\n", $errors ) ) . '</pre></details></td><td>'; if ( in_array( $job['status'], array( 'created', 'validating', 'importing', 'promoting' ), true ) ) { echo '<button type="button" class="button" data-bible-admin-action="cancel-import" data-id="' . esc_attr( $job['id'] ) . '">' . esc_html__( 'Cancel import', 'videohub360-studio' ) . '</button> '; } if ( in_array( $job['status'], array( 'failed', 'cancelled' ), true ) ) { echo '<button type="button" class="button" data-bible-admin-action="clean-import" data-id="' . esc_attr( $job['id'] ) . '">' . esc_html__( 'Clean failed import', 'videohub360-studio' ) . '</button>'; } echo '</td></tr>'; }
        echo '</tbody></table><h2>' . esc_html__( 'Import translation', 'videohub360-studio' ) . '</h2><form id="vh360-bible-import-form" enctype="multipart/form-data">';
        $fields = array( 'translationKey' => __( 'Translation key', 'videohub360-studio' ), 'name' => __( 'Translation name', 'videohub360-studio' ), 'abbreviation' => __( 'Abbreviation', 'videohub360-studio' ), 'language' => __( 'Language', 'videohub360-studio' ), 'sourceName' => __( 'Dataset source', 'videohub360-studio' ), 'sourceUrl' => __( 'Source URL', 'videohub360-studio' ), 'licenseName' => __( 'License name', 'videohub360-studio' ), 'licenseUrl' => __( 'License URL', 'videohub360-studio' ), 'datasetVersion' => __( 'Dataset version', 'videohub360-studio' ) );
        echo '<p><label>' . esc_html__( 'CSV file', 'videohub360-studio' ) . '<br><input type="file" name="file" accept=".csv,text/csv" required></label></p>'; foreach ( $fields as $name => $label ) { $req = in_array( $name, array( 'translationKey', 'name', 'abbreviation', 'language', 'sourceName', 'licenseName', 'datasetVersion' ), true ) ? ' required' : ''; echo '<p><label>' . esc_html( $label ) . '<br><input name="' . esc_attr( $name ) . '"' . $req . '></label></p>'; }
        echo '<p><label>' . esc_html__( 'Attribution', 'videohub360-studio' ) . '<br><textarea name="attribution"></textarea></label></p><p><label><input type="checkbox" name="attributionRequired" value="1"> ' . esc_html__( 'Attribution is required by this license.', 'videohub360-studio' ) . '</label></p><p><label><input type="checkbox" name="permissionConfirmed" value="1" required> ' . esc_html__( 'I confirm permission to use this file.', 'videohub360-studio' ) . '</label></p><button class="button button-primary">' . esc_html__( 'Import translation', 'videohub360-studio' ) . '</button></form><pre id="vh360-bible-import-progress" aria-live="polite"></pre></div>';
    }
}
