<?php
if ( ! defined( 'ABSPATH' ) ) { exit; }
class VH360_Studio_Bible_Repository {
    const LIMIT = 50;
    public function list_translations(){global $wpdb;$t=VH360_Studio_Database::bible_translations_table_name();return $wpdb->get_results($wpdb->prepare("SELECT translation_key AS translationKey,name,abbreviation,language,source_name AS sourceName,source_url AS sourceUrl,license_name AS licenseName,license_url AS licenseUrl,attribution,attribution_required AS attributionRequired,dataset_version AS datasetVersion,source_hash AS sourceHash,verse_count AS verseCount,book_count AS bookCount,imported_at AS importedAt FROM {$t} WHERE status=%s ORDER BY name",'installed'),ARRAY_A);}
    public function translation_exists($key){global $wpdb;$t=VH360_Studio_Database::bible_translations_table_name();return (bool)$wpdb->get_var($wpdb->prepare("SELECT COUNT(*) FROM {$t} WHERE translation_key=%s AND status='installed'",sanitize_key($key)));}
    public function get_translation($key){global $wpdb;$t=VH360_Studio_Database::bible_translations_table_name();return $wpdb->get_row($wpdb->prepare("SELECT * FROM {$t} WHERE translation_key=%s AND status='installed'",sanitize_key($key)),ARRAY_A);}
    public function list_books($translation_key){global $wpdb;$v=VH360_Studio_Database::bible_verses_table_name();return $wpdb->get_results($wpdb->prepare("SELECT book_key AS bookKey, MIN(book_name) AS name, MIN(book_order) AS bookOrder, COUNT(*) AS verseRows FROM {$v} WHERE translation_key=%s GROUP BY book_key ORDER BY bookOrder",sanitize_key($translation_key)),ARRAY_A);}
    public function list_chapters($translation_key,$book_key){global $wpdb;$v=VH360_Studio_Database::bible_verses_table_name();return array_map('absint',$wpdb->get_col($wpdb->prepare("SELECT DISTINCT chapter_number FROM {$v} WHERE translation_key=%s AND book_key=%s ORDER BY chapter_number",sanitize_key($translation_key),sanitize_key($book_key))));}
    public function get_chapter($translation_key,$book_key,$chapter){$tr=$this->get_translation($translation_key); if(!$tr){return new WP_Error('vh360_bible_translation_missing',__('This translation is no longer installed.','videohub360-studio'),array('status'=>404));}$key='vh360_bible_'.sanitize_key($translation_key).'_'.sanitize_key($book_key).'_'.absint($chapter).'_'.$tr['source_hash'];$cached=wp_cache_get($key,'vh360_studio'); if(false!==$cached){return $cached;} global $wpdb;$v=VH360_Studio_Database::bible_verses_table_name();$rows=$wpdb->get_results($wpdb->prepare("SELECT book_key AS bookKey,book_name AS bookName,chapter_number AS chapter,verse_number AS verse,verse_suffix AS suffix,verse_text AS text,verse_status AS status FROM {$v} WHERE translation_key=%s AND book_key=%s AND chapter_number=%d ORDER BY verse_number,verse_suffix",sanitize_key($translation_key),sanitize_key($book_key),absint($chapter)),ARRAY_A);$rows=array_values(array_filter($rows,function($r){return 'present'===$r['status'] && trim($r['text'])!=='';}));wp_cache_set($key,$rows,'vh360_studio',HOUR_IN_SECONDS);return $rows;}
    public function get_passage($translation_key,$ranges){$out=array();foreach($ranges as $range){for($c=absint($range['start_chapter']);$c<=absint($range['end_chapter']);$c++){foreach($this->get_chapter($translation_key,$range['book_key'],$c) as $row){$v=absint($row['verse']); if(($c==$range['start_chapter']&&$v<absint($range['start_verse']))||($c==$range['end_chapter']&&$v>absint($range['end_verse']))){continue;} $out[]=$row; if(count($out)>self::LIMIT){return new WP_Error('vh360_bible_passage_too_large',__('Bible passages are limited to 50 verses.','videohub360-studio'),array('status'=>400));}}}} return $out;}
    public function resolve_reference($translation_key,$reference){$parser=new VH360_Studio_Bible_Reference_Parser();$ranges=$parser->parse($reference); if(is_wp_error($ranges)){return $ranges;} $verses=$this->get_passage($translation_key,$ranges); if(is_wp_error($verses)){return $verses;} if(empty($verses)){return new WP_Error('vh360_bible_reference_empty',__('Reference could not be resolved.','videohub360-studio'),array('status'=>404));}$tr=$this->get_translation($translation_key);$book=VH360_Studio_Bible_Books::get($ranges[0]['book_key']);return array('translation'=>array('translationKey'=>$tr['translation_key'],'translationLabel'=>$tr['abbreviation'],'datasetVersion'=>$tr['dataset_version'],'sourceHash'=>$tr['source_hash'],'attribution'=>$tr['attribution'],'attributionRequired'=>(bool)$tr['attribution_required']),'reference'=>$this->display_reference($book['default_name'],$ranges[0]),'ranges'=>$ranges,'verses'=>$verses);}
    private function display_reference($book,$r){$same=$r['start_chapter']===$r['end_chapter']; if(999===$r['end_verse']){return $book.' '.$r['start_chapter'];} if($same&&$r['start_verse']===$r['end_verse']){return $book.' '.$r['start_chapter'].':'.$r['start_verse'];} return $book.' '.$r['start_chapter'].':'.$r['start_verse'].'–'.($same?'':$r['end_chapter'].':').$r['end_verse'];}
    public static function clear_translation_cache($translation_key){function_exists('wp_cache_flush_group') ? wp_cache_flush_group('vh360_studio') : wp_cache_flush();}
}
