<?php

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

/**
 * Manage root-level files required by browsers for PWA + OneSignal.
 *
 * Why this exists:
 * - Browsers require service workers to be fetched from the scope they control (typically site root).
 * - Many hosts/CDNs do not forward WordPress rewrite endpoints consistently for SW/manifest requests.
 * - OneSignal specifically looks for /OneSignalSDKWorker.js and /OneSignalSDK.sw.js at the web root.
 *
 * This class ensures those files exist as real files so 404s do not return.
 */
final class VH360_PWA_Root_Files {
	/**
	 * Root-level filenames we manage.
	 */
	private const FILES = array(
		'vh360-manifest.json',
		'vh360-sw.js',
		'vh360-offline.html',
		'OneSignalSDKWorker.js',
		'OneSignalSDKUpdaterWorker.js',
		'OneSignalSDK.sw.js',
	);

	/**
	 * Ensure all required files exist.
	 */
	public static function ensure_root_files() : void {
		// Avoid running during install/upgrade steps where ABSPATH may not be stable.
		if ( ! defined( 'ABSPATH' ) || ! is_string( ABSPATH ) ) {
			return;
		}

		$root = trailingslashit( ABSPATH );

		// Best-effort filesystem init.
		global $wp_filesystem;
		if ( empty( $wp_filesystem ) ) {
			require_once ABSPATH . 'wp-admin/includes/file.php';
			// phpcs:ignore WordPressVIPMinimum.Functions.RestrictedFunctions.file_ops_wp_filesystem
			WP_Filesystem();
		}

		self::maybe_write_manifest( $root );
		self::maybe_write_offline_page( $root );
		self::maybe_write_vh360_sw( $root );
		self::maybe_write_onesignal_workers( $root );
	}

	private static function maybe_write_manifest( string $root ) : void {
		$path = $root . 'vh360-manifest.json';
		$manifest = vh360_pwa_build_manifest();
		$manifest['generated_by'] = 'VH360 PWA & App plugin';
		$manifest['generated_at'] = gmdate( 'c' );
		$written = self::write_managed_file( $path, wp_json_encode( $manifest, JSON_UNESCAPED_SLASHES | JSON_PRETTY_PRINT ) . "\n", 'vh360-manifest.json' );
		update_option( 'vh360_pwa_root_manifest_write_status', array( 'success' => $written, 'path' => $path, 'generated_at' => time() ) );
	}

	private static function maybe_write_offline_page( string $root ) : void {
		$path = $root . 'vh360-offline.html';
		$opts = vh360_pwa_get_options();
		$app = esc_html( (string) $opts['app_name'] );
		$bg = esc_attr( (string) ( $opts['splash_background_color'] ?: $opts['background_color'] ) );
		$theme = esc_attr( (string) $opts['theme_color'] );
		$html = '<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>Offline</title><style>body{font-family:system-ui,-apple-system,Segoe UI,Roboto,Helvetica,Arial,sans-serif;margin:0;min-height:100vh;display:grid;place-items:center;padding:40px;background:' . $bg . ';color:#fff}main{max-width:520px;text-align:center}a{color:' . $theme . '}</style></head><body><!-- VH360 Managed File: vh360-offline.html --><main><h1>' . $app . ' is offline</h1><p>Please check your connection and try again.</p><p><a href="/">Return home</a></p></main></body></html>' . "\n";
		self::write_managed_file( $path, $html, 'vh360-offline.html' );
	}

	private static function maybe_write_vh360_sw( string $root ) : void {
		$path = $root . 'vh360-sw.js';
		self::write_managed_file( $path, vh360_pwa_build_sw_script(), 'vh360-sw.js' );
	}

	private static function maybe_write_onesignal_workers( string $root ) : void {
		// OneSignal requires both filenames at the site root. Use a managed wrapper that imports OneSignal's SW
		// and then imports VH360's SW for offline fallback.
		// Chrome requires some event handlers (notably 'message') to be registered during initial evaluation.
		// Add a harmless no-op handler before importing OneSignal to avoid warnings.
		$wrapper = "/* VH360 Managed File: OneSignal service worker wrapper */\n" .
			"self.addEventListener('message', function () {});\n" .
			"try {\n" .
			"  importScripts('https://cdn.onesignal.com/sdks/web/" . esc_js( VH360_PWA_ONESIGNAL_SDK_VERSION ) . "/OneSignalSDK.sw.js');\n" .
			"} catch (e) {}\n" .
			"try {\n" .
			"  importScripts('/vh360-sw.js');\n" .
			"} catch (e) {}\n";

		foreach ( array( 'OneSignalSDKWorker.js', 'OneSignalSDK.sw.js', 'OneSignalSDKUpdaterWorker.js' ) as $file ) {
			$path = $root . $file;

			// If missing, create.
			if ( ! file_exists( $path ) ) {
				self::write_file( $path, $wrapper );
				continue;
			}

			// If it's one of our managed files but was generated by an older version (e.g. missing the early
			// 'message' handler), repair it. Never overwrite non-managed/custom files.
			$existing = @file_get_contents( $path ); // phpcs:ignore WordPressVIPMinimum.Functions.RestrictedFunctions.file_ops_file_get_contents
			if ( is_string( $existing )
				&& strpos( $existing, 'VH360 Managed File' ) !== false
				&& strpos( $existing, "addEventListener('message'" ) === false
			) {
				self::write_file( $path, $wrapper );
			}
		}
	}

	private static function write_managed_file( string $path, string $contents, string $marker ) : bool {
		if ( file_exists( $path ) ) {
			$existing = @file_get_contents( $path );
			if ( ! is_string( $existing ) || false === strpos( $existing, 'VH360 Managed File' ) && false === strpos( $existing, 'VH360 PWA & App plugin' ) ) {
				return false;
			}
		}
		if ( 'vh360-manifest.json' !== $marker && false === strpos( $contents, 'VH360 Managed File' ) ) {
			$contents = '/* VH360 Managed File: ' . $marker . ' */' . "\n" . $contents;
		}
		return self::write_file( $path, $contents );
	}

	private static function write_file( string $path, string $contents ) : bool {
		global $wp_filesystem;

		// Prefer WP_Filesystem when available.
		if ( $wp_filesystem && is_object( $wp_filesystem ) && method_exists( $wp_filesystem, 'put_contents' ) ) {
			return (bool) $wp_filesystem->put_contents( $path, $contents, FS_CHMOD_FILE );
		}

		// Fallback.
		// phpcs:ignore WordPressVIPMinimum.Functions.RestrictedFunctions.file_ops_file_put_contents
		return false !== @file_put_contents( $path, $contents );
	}
}
