<?php
if (!defined('ABSPATH')) exit;
class VideoHub360_Consent_Privacy_Tools {
    public function __construct() { add_action('admin_init', array($this,'policy')); add_filter('wp_privacy_personal_data_exporters', array($this,'exporters')); add_filter('wp_privacy_personal_data_erasers', array($this,'erasers')); }
    public function policy() { if (!function_exists('wp_add_privacy_policy_content')) return; wp_add_privacy_policy_content('VideoHub360', wp_kses_post(wpautop(__('VideoHub360 may use WordPress authentication cookies for accounts and sessions, a first-party consent preference cookie, browser storage for optional interface preferences, aggregate video advertisement click measurement when analytics consent is available, and push-notification tools only after a visitor takes an explicit subscription action. Site administrators are responsible for additional plugins, embeds, and advertising widgets they configure.', 'videohub360')))); }
    public function exporters($e) { $e['videohub360-legacy-ad-clicks'] = array('exporter_friendly_name'=>__('VideoHub360 legacy ad click records','videohub360'),'callback'=>array($this,'export')); return $e; }
    public function erasers($e) { $e['videohub360-legacy-ad-clicks'] = array('eraser_friendly_name'=>__('VideoHub360 legacy ad click records','videohub360'),'callback'=>array($this,'erase')); return $e; }
    public function export($email, $page=1) { $user = get_user_by('email', $email); if (!$user) return array('data'=>array(),'done'=>true); $data=array(); $q = new WP_Query(array('post_type'=>'videohub360','posts_per_page'=>50,'paged'=>max(1,absint($page)),'fields'=>'ids','post_status'=>'any')); foreach($q->posts as $post_id) foreach(array('preroll','midroll','postroll') as $type) { $rows=get_post_meta($post_id,'_vh360_ad_clicks_'.$type,true); if (!is_array($rows)) continue; foreach($rows as $row) if (absint($row['user_id'] ?? 0)===$user->ID) $data[] = array('group_id'=>'videohub360-legacy-ad-clicks','group_label'=>__('VideoHub360 legacy ad click records','videohub360'),'item_id'=>$post_id.'-'.$type,'data'=>array(array('name'=>__('Video ID','videohub360'),'value'=>$post_id),array('name'=>__('Advertisement type','videohub360'),'value'=>$type),array('name'=>__('Timestamp','videohub360'),'value'=>sanitize_text_field($row['timestamp'] ?? '')))); } return array('data'=>$data,'done'=>!$q->max_num_pages || $page >= $q->max_num_pages); }
    public function erase($email, $page=1) { $user=get_user_by('email',$email); if(!$user) return array('items_removed'=>false,'items_retained'=>false,'messages'=>array(),'done'=>true); $removed=false; $q=new WP_Query(array('post_type'=>'videohub360','posts_per_page'=>25,'paged'=>max(1,absint($page)),'fields'=>'ids','post_status'=>'any')); foreach($q->posts as $post_id) foreach(array('preroll','midroll','postroll') as $type) { $key='_vh360_ad_clicks_'.$type; $rows=get_post_meta($post_id,$key,true); if(!is_array($rows)) continue; $new=array_values(array_filter($rows,function($row) use($user){ return absint($row['user_id'] ?? 0)!==$user->ID; })); if(count($new)!==count($rows)){ update_post_meta($post_id,$key,$new); $removed=true; } } return array('items_removed'=>$removed,'items_retained'=>false,'messages'=>array(),'done'=>!$q->max_num_pages || $page >= $q->max_num_pages); }
}
