<?php
if (!defined('ABSPATH')) exit;
class VideoHub360_Consent_Admin {
    private $manager;
    public function __construct($manager) { $this->manager = $manager; add_action('admin_menu', array($this,'menu')); add_action('admin_init', array($this,'settings')); add_action('admin_enqueue_scripts', array($this,'assets')); }
    public function menu() { add_submenu_page('edit.php?post_type=videohub360', __('Privacy & Consent','videohub360'), __('Privacy & Consent','videohub360'), 'manage_options', 'videohub360-privacy-consent', array($this,'page')); }
    public function settings() { register_setting('vh360_consent_settings_group', VideoHub360_Consent_Manager::OPTION, array('sanitize_callback'=>array('VideoHub360_Consent_Manager','sanitize_settings'))); }
    public function assets($hook) { if (false !== strpos($hook, 'videohub360-privacy-consent')) { wp_enqueue_style('vh360-consent-admin', VIDEOHUB360_PLUGIN_URL . 'assets/css/consent-admin.css', array(), VIDEOHUB360_VERSION); wp_enqueue_script('vh360-consent-admin', VIDEOHUB360_PLUGIN_URL . 'assets/js/consent-admin.js', array(), VIDEOHUB360_VERSION, true); } }
    public function page() { if (!current_user_can('manage_options')) return; $s = $this->manager->get_settings(); ?>
    <div class="wrap vh360-consent-admin"><h1><?php esc_html_e('Privacy & Consent', 'videohub360'); ?></h1><p><?php esc_html_e('Configure VideoHub360 consent behavior. This tool helps centralize choices but does not guarantee legal compliance.', 'videohub360'); ?></p>
    <form method="post" action="options.php"><?php settings_fields('vh360_consent_settings_group'); ?><table class="form-table" role="presentation">
    <tr><th><label for="vh360_consent_mode"><?php esc_html_e('Consent mode','videohub360'); ?></label></th><td><select id="vh360_consent_mode" name="<?php echo esc_attr(VideoHub360_Consent_Manager::OPTION); ?>[mode]"><?php foreach(array('disabled'=>__('Disabled','videohub360'),'notice'=>__('Notice Only','videohub360'),'opt_out'=>__('Opt-Out','videohub360'),'strict'=>__('Strict Opt-In (recommended)','videohub360')) as $v=>$l) echo '<option value="'.esc_attr($v).'" '.selected($s['mode'],$v,false).'>'.esc_html($l).'</option>'; ?></select><p class="description"><?php esc_html_e('Disabled preserves existing behavior and allows another consent plugin to control the site. Strict Opt-In is recommended when enabling VideoHub360 consent.', 'videohub360'); ?></p></td></tr>
    <?php $fields = array('policy_version'=>__('Policy version','videohub360'),'expiration_days'=>__('Consent expiration days','videohub360'),'banner_heading'=>__('Banner heading','videohub360'),'banner_description'=>__('Banner description','videohub360'),'privacy_policy_url'=>__('Privacy Policy URL','videohub360'),'accept_all_text'=>__('Accept All button text','videohub360'),'reject_optional_text'=>__('Reject Optional button text','videohub360'),'manage_preferences_text'=>__('Manage Preferences button text','videohub360'),'save_preferences_text'=>__('Save Preferences button text','videohub360'),'privacy_choices_text'=>__('Privacy Choices link text','videohub360')); foreach($fields as $key=>$label): ?>
    <tr><th><label for="vh360_<?php echo esc_attr($key); ?>"><?php echo esc_html($label); ?></label></th><td><input class="regular-text" id="vh360_<?php echo esc_attr($key); ?>" name="<?php echo esc_attr(VideoHub360_Consent_Manager::OPTION); ?>[<?php echo esc_attr($key); ?>]" value="<?php echo esc_attr($s[$key]); ?>" /></td></tr>
    <?php endforeach; ?>
    <tr><th><?php esc_html_e('Privacy Policy page','videohub360'); ?></th><td><?php wp_dropdown_pages(array('name'=>VideoHub360_Consent_Manager::OPTION.'[privacy_policy_page_id]','selected'=>absint($s['privacy_policy_page_id']),'show_option_none'=>__('Select a page','videohub360'))); ?></td></tr>
    <tr><th><?php esc_html_e('Persistent Privacy Choices control','videohub360'); ?></th><td><label><input type="checkbox" name="<?php echo esc_attr(VideoHub360_Consent_Manager::OPTION); ?>[show_persistent_control]" value="1" <?php checked($s['show_persistent_control'],1); ?> /> <?php esc_html_e('Show a persistent control that reopens preferences.','videohub360'); ?></label></td></tr>
    <tr><th><?php esc_html_e('Banner position','videohub360'); ?></th><td><select name="<?php echo esc_attr(VideoHub360_Consent_Manager::OPTION); ?>[banner_position]"><option value="bottom" <?php selected($s['banner_position'],'bottom'); ?>><?php esc_html_e('Bottom','videohub360'); ?></option><option value="top" <?php selected($s['banner_position'],'top'); ?>><?php esc_html_e('Top','videohub360'); ?></option></select></td></tr>
    </table><h2><?php esc_html_e('Activity Feed and third-party widgets','videohub360'); ?></h2><p><?php esc_html_e('VideoHub360 can block its own personalized Activity Feed ad slot until advertising consent. Unrelated plugins may enqueue scripts outside widget markup; register known services or script handles with VideoHub360 consent filters so they can be controlled.', 'videohub360'); ?></p><?php submit_button(); ?></form></div><?php }
}
