<?php
if (!defined('ABSPATH')) exit;
class VH360_Giving_Transactions {
    public static function create($data){ global $wpdb; $t=VH360_Giving_Database::get_transactions_table(); $now=current_time('mysql'); $row=wp_parse_args($data,array('status'=>'pending','gateway'=>'stripe','gateway_mode'=>'payment','source'=>'dashboard','anonymous'=>0,'created_at'=>$now,'updated_at'=>$now)); $wpdb->insert($t,$row); return $wpdb->insert_id; }
    public static function update($id,$data){ global $wpdb; $data['updated_at']=current_time('mysql'); return $wpdb->update(VH360_Giving_Database::get_transactions_table(),$data,array('id'=>absint($id))); }
    public static function get($id){ global $wpdb; $t=VH360_Giving_Database::get_transactions_table(); return $wpdb->get_row($wpdb->prepare("SELECT * FROM {$t} WHERE id=%d",$id)); }
    public static function for_user($user_id,$limit=50,$date_from='',$date_to='',$statuses=array('paid','refunded')){ global $wpdb; $t=VH360_Giving_Database::get_transactions_table(); $where=array('user_id=%d'); $params=array(absint($user_id)); $statuses=array_filter(array_map('sanitize_key',(array)$statuses)); if(!empty($statuses)){ $placeholders=implode(',',array_fill(0,count($statuses),'%s')); $where[]="status IN ({$placeholders})"; $params=array_merge($params,$statuses); } if($date_from&&preg_match('/^\d{4}-\d{2}-\d{2}$/',$date_from)){ $where[]='COALESCE(given_at, created_at) >= %s'; $params[]=$date_from.' 00:00:00'; } if($date_to&&preg_match('/^\d{4}-\d{2}-\d{2}$/',$date_to)){ $where[]='COALESCE(given_at, created_at) <= %s'; $params[]=$date_to.' 23:59:59'; } $sql="SELECT * FROM {$t} WHERE ".implode(' AND ',$where).' ORDER BY created_at DESC LIMIT %d'; $params[]=absint($limit); return $wpdb->get_results($wpdb->prepare($sql,$params)); }
    public static function total($where='1=1'){ global $wpdb; $t=VH360_Giving_Database::get_transactions_table(); return (float)$wpdb->get_var("SELECT COALESCE(SUM(amount),0) FROM {$t} WHERE status='paid' AND {$where}"); }
    public static function invoice_exists($invoice_id){ global $wpdb; if(!$invoice_id) return false; $t=VH360_Giving_Database::get_transactions_table(); return (int)$wpdb->get_var($wpdb->prepare("SELECT COUNT(*) FROM {$t} WHERE stripe_invoice_id=%s OR gateway_transaction_id=%s",sanitize_text_field($invoice_id),sanitize_text_field($invoice_id)))>0; }
}
